version: 2


sources:
  - name: raw
    schema: raw         
    database: CRYPTO_DB      
    tables:
      - name: raw_coins_markets
      - name: raw_coins_trending

models:
  - name: stg_coins_markets
    description: "Staging for CoinGecko coins/markets API"
    columns:
      - name: coin_id
        tests: [not_null, unique]
      - name: current_price
        tests: [not_null]
      - name: last_updated
        tests: [not_null]

  - name: stg_coins_trending
    description: "Staging for trending coins"
    columns:
      - name: coin_id
        tests: [not_null]
      - name: score
        tests: [not_null]

  - name: stg_trending_categories
    description: "Staging for trending categories"
    columns:
      - name: category_id
        tests: [not_null, unique]

  - name: stg_trending_nfts
    description: "Staging for trending NFTs"
    columns:
      - name: nft_id
        tests: [not_null, unique]
